name: Package
on:
  release:
    types: [ published ]
jobs:
  atilo-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with: 
          python-version: 3.11.1

      - name: Install Modules
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Package
        id: package
        run: |
          sudo apt update
          sudo apt install curl -y
          mkdir -p -v build/atilo/DEBIAN build/atilo-cn/DEBIAN build/debs
          chmod -v 700 build/atilo/DEBIAN
          cd build
          curl -L https://u.nu/dhgt9 -o atilo.deb
          dpkg -X atilo.deb atilo/
          dpkg -e atilo.deb atilo/DEBIAN
          export ATILO_VERSION=$(../atilo |head -n1 |awk '{print $2}')
          sed -i -E "s/^Version.*/Version:\ ${ATILO_VERSION}/g" atilo/DEBIAN/control
          cp ../atilo atilo/data/data/com.termux/files/usr/bin/atilo
          dpkg -b atilo debs/atilo.deb
          echo "::set-output name=STATUS::success"
          export debs=$(realpath debs/)

      - name: Upload
        if: steps.package.outputs.STATUS == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: debs
          path: "/home/runner/work/atilo/atilo/build/debs"
