name: Test

on:

  push:

    branch: [ master ]

  pull_request:

    branch: [ master ]

  release:

    types: [ published ]

jobs:

  atilo-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: Setup Python

        uses: actions/setup-python@v1

        with: 

          python-version: 3.11.1

      - name: Install Modules

        run: |

          python -m pip install -U pip

          pip install -r requirements.txt

        

      - name: Test

        id: test

        run: |

          ./atilo help

          ./atilo images

          ./atilo pull alpine

          ./atilo clean

          ./atilo remove alpine

          echo "::set-output name=STATUS::success"
